from __future__ import annotations

import sys
from html import escape
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from plotly.subplots import make_subplots


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

PORTFOLIO_CSV_PATH = PROJECT_ROOT / "output" / "unified_campaign_daily.csv"
GLOBAL_ADS_RAW_PATH = PROJECT_ROOT / "data" / "public" / "raw_global_ads_performance_dataset.csv"
GLOBAL_ADS_DAILY_PATH = PROJECT_ROOT / "data" / "public" / "global_ads_performance_daily.csv"
DEFAULT_DATASET_ID = "global_ads_performance"
METRIC_COLUMNS = ["impressions", "clicks", "spend", "conversions", "revenue"]
REQUIRED_COLUMNS = [
    "date",
    "source",
    "campaign_id",
    "campaign_name",
    "impressions",
    "clicks",
    "spend",
    "conversions",
    "ctr",
    "cpc",
    "cpa",
]
DATASETS = {
    "global_ads_performance": {
        "label": "Kaggle global ads performance",
        "source_name": "GlobalAdsPerformance_GoogleMetaTikTok.csv",
        "source_detail": "Kaggle Global Ads Performance: Google, Meta, TikTok",
        "freshness_label": "Kaggle CC0 public dataset",
        "as_of": "Dec 31, 2024",
    },
    "portfolio": {
        "label": "Portfolio multi-platform sample",
        "source_name": "UnifiedPaidMedia",
        "source_detail": "Generated by the companion Airflow pipeline",
        "freshness_label": "Generated local demo extract",
        "as_of": "",
    },
}
SOURCE_LABELS = {
    "google_ads": "Google Ads",
    "meta_ads": "Meta",
    "Meta Ads": "Meta",
    "tiktok_ads": "TikTok",
    "TikTok Ads": "TikTok",
    "youtube_ads": "YouTube",
    "microsoft_ads": "Microsoft Ads",
    "other_ads": "Other",
}
PLATFORM_COLORS = {
    "Google Ads": "#12b8ba",
    "Meta": "#2563eb",
    "Meta Ads": "#2563eb",
    "TikTok": "#d92782",
    "TikTok Ads": "#d92782",
    "YouTube": "#f59e0b",
    "Microsoft Ads": "#8057e8",
    "Other": "#8f99a8",
}
SOURCE_MEDIUM = {
    "Google Ads": "Paid Search",
    "Meta": "Paid Social",
    "Meta Ads": "Paid Social",
    "TikTok": "Paid Social",
    "TikTok Ads": "Paid Social",
    "YouTube": "Video",
    "Microsoft Ads": "Paid Search",
    "Other": "Affiliate / Other",
}
METRIC_ACCENTS = {
    "Spend": "#2563eb",
    "Conversions": "#0f766e",
    "CPA": "#db2777",
    "CTR": "#f59e0b",
    "CPC": "#7c3aed",
    "Revenue": "#14b8a6",
    "ROAS": "#ef4444",
}


def safe_divide(numerator: float, denominator: float) -> float:
    return 0.0 if denominator == 0 else numerator / denominator


def normalize_source_label(value: object) -> str:
    text = "" if pd.isna(value) else str(value)
    return SOURCE_LABELS.get(text, text or "Uploaded")


def normalize_medium_label(row: pd.Series) -> str:
    explicit = row.get("source_medium") or row.get("medium_label")
    if explicit and not pd.isna(explicit):
        return str(explicit)
    source_label = normalize_source_label(row.get("source"))
    return SOURCE_MEDIUM.get(source_label, "Paid Media")


def infer_industry(campaign_name: object) -> str:
    text = "" if pd.isna(campaign_name) else str(campaign_name)
    for marker in [" Search ", " Display ", " Shopping ", " Video "]:
        if marker in text:
            return text.split(marker, 1)[0]
    return "Unknown"


def prepare_campaign_data(df: pd.DataFrame) -> pd.DataFrame:
    missing_columns = sorted(set(REQUIRED_COLUMNS) - set(df.columns))
    if missing_columns:
        joined = ", ".join(missing_columns)
        raise ValueError(f"Uploaded CSV is missing required columns: {joined}")

    prepared = df.copy()
    if "account_id" not in prepared.columns:
        prepared["account_id"] = ""
    if "segment" not in prepared.columns:
        prepared["segment"] = ""
    if "total_conversion" not in prepared.columns:
        prepared["total_conversion"] = prepared["conversions"]
    if "revenue" not in prepared.columns:
        prepared["revenue"] = 0
    if "roas" not in prepared.columns:
        prepared["roas"] = 0
    if "dataset" not in prepared.columns:
        prepared["dataset"] = "uploaded"

    prepared["date"] = pd.to_datetime(prepared["date"], errors="coerce", format="mixed").dt.normalize()
    if prepared["date"].isna().any():
        raise ValueError("CSV contains rows with invalid dates.")

    for column in METRIC_COLUMNS + ["ctr", "cpc", "cpa", "total_conversion", "roas"]:
        prepared[column] = pd.to_numeric(prepared[column], errors="coerce").fillna(0)

    prepared["ctr"] = prepared.apply(lambda row: row["ctr"] or safe_divide(row["clicks"], row["impressions"]), axis=1)
    prepared["cpc"] = prepared.apply(lambda row: row["cpc"] or safe_divide(row["spend"], row["clicks"]), axis=1)
    prepared["cpa"] = prepared.apply(lambda row: row["cpa"] or safe_divide(row["spend"], row["conversions"]), axis=1)
    prepared["roas"] = prepared.apply(lambda row: row["roas"] or safe_divide(row["revenue"], row["spend"]), axis=1)
    if "source_label" not in prepared.columns:
        prepared["source_label"] = prepared["source"].map(normalize_source_label)
    else:
        prepared["source_label"] = prepared["source_label"].map(normalize_source_label)
    prepared["source_medium"] = prepared.apply(normalize_medium_label, axis=1)
    if "country" not in prepared.columns:
        prepared["country"] = prepared["segment"].replace("", "Unknown")
    if "industry" not in prepared.columns:
        prepared["industry"] = prepared["campaign_name"].map(infer_industry)
    return prepared.sort_values(["date", "source_label", "campaign_name"]).reset_index(drop=True)


def ensure_dashboard_columns(df: pd.DataFrame) -> pd.DataFrame:
    prepared = df.copy()
    if "account_id" not in prepared.columns:
        prepared["account_id"] = ""
    if "segment" not in prepared.columns:
        prepared["segment"] = ""
    if "total_conversion" not in prepared.columns:
        prepared["total_conversion"] = prepared["conversions"]
    if "revenue" not in prepared.columns:
        prepared["revenue"] = 0
    if "roas" not in prepared.columns:
        prepared["roas"] = 0
    if "dataset" not in prepared.columns:
        prepared["dataset"] = "portfolio"
    if "source_label" not in prepared.columns:
        prepared["source_label"] = prepared["source"].map(normalize_source_label)
    else:
        prepared["source_label"] = prepared["source_label"].map(normalize_source_label)
    if "source_medium" not in prepared.columns:
        prepared["source_medium"] = prepared.apply(normalize_medium_label, axis=1)
    if "country" not in prepared.columns:
        prepared["country"] = prepared["segment"].replace("", "Unknown")
    if "industry" not in prepared.columns:
        prepared["industry"] = prepared["campaign_name"].map(infer_industry)
    return prepared


def default_output_is_stale() -> bool:
    if not PORTFOLIO_CSV_PATH.exists():
        return True

    from marketing_data_ops.io import SOURCE_FILES

    output_mtime = PORTFOLIO_CSV_PATH.stat().st_mtime
    dependency_paths = [PROJECT_ROOT / "config" / "pipeline.yml"]
    dependency_paths.extend(PROJECT_ROOT / path for path in SOURCE_FILES.values())
    return any(path.exists() and path.stat().st_mtime > output_mtime for path in dependency_paths)


def load_portfolio_campaign_data() -> tuple[pd.DataFrame, bool, str]:
    generated = False
    if default_output_is_stale():
        from marketing_data_ops.pipeline import run_pipeline

        run_pipeline(PROJECT_ROOT)
        generated = True

    df = pd.read_csv(PORTFOLIO_CSV_PATH)
    source_path = PORTFOLIO_CSV_PATH.relative_to(PROJECT_ROOT).as_posix()
    return prepare_campaign_data(df), generated, source_path


def normalize_global_ads_performance(raw: pd.DataFrame) -> pd.DataFrame:
    source_map = {
        "Google Ads": "google_ads",
        "Meta Ads": "meta_ads",
        "Meta": "meta_ads",
        "TikTok Ads": "tiktok_ads",
        "TikTok": "tiktok_ads",
    }
    medium_map = {
        "Display": ("display", "Display"),
        "Search": ("paid_search", "Paid Search"),
        "Shopping": ("paid_shopping", "Paid Shopping"),
        "Video": ("paid_video", "Paid Video"),
    }
    rows = raw.copy().reset_index(drop=True)
    rows["source_label"] = rows["platform"].map(normalize_source_label)
    rows["source"] = rows["platform"].map(source_map).fillna(rows["source_label"].str.lower().str.replace(" ", "_"))
    medium_pairs = rows["campaign_type"].map(medium_map)
    rows["medium"] = medium_pairs.map(lambda pair: pair[0] if isinstance(pair, tuple) else "uploaded")
    rows["medium_label"] = medium_pairs.map(lambda pair: pair[1] if isinstance(pair, tuple) else "Uploaded")
    rows["source_medium"] = rows["medium_label"]
    rows["campaign_id"] = [f"GA-{index + 1:05d}" for index in rows.index]
    rows["campaign_name"] = rows["industry"].astype(str) + " " + rows["campaign_type"].astype(str) + " " + rows["country"].astype(str)
    rows["segment"] = rows["country"]
    rows["spend"] = rows["ad_spend"]
    rows["total_conversion"] = rows["conversions"]
    rows["ctr"] = rows["CTR"]
    rows["cpc"] = rows["CPC"]
    rows["cpa"] = rows["CPA"]
    rows["roas"] = rows["ROAS"]
    rows["dataset"] = "global_ads_performance"
    rows["account_id"] = "kaggle-global-ads"
    return prepare_campaign_data(rows)


def load_global_ads_performance_data() -> tuple[pd.DataFrame, str]:
    if GLOBAL_ADS_DAILY_PATH.exists():
        df = pd.read_csv(GLOBAL_ADS_DAILY_PATH)
        return prepare_campaign_data(df), GLOBAL_ADS_DAILY_PATH.relative_to(PROJECT_ROOT).as_posix()

    raw = pd.read_csv(GLOBAL_ADS_RAW_PATH)
    return normalize_global_ads_performance(raw), GLOBAL_ADS_RAW_PATH.relative_to(PROJECT_ROOT).as_posix()


def load_dashboard_dataset(dataset_id: str) -> tuple[pd.DataFrame, str, str]:
    if dataset_id == "global_ads_performance":
        df, source_path = load_global_ads_performance_data()
        return df, DATASETS[dataset_id]["source_name"], source_path

    df, generated, source_path = load_portfolio_campaign_data()
    source_name = f"UnifiedPaidMedia_v{df['date'].max().date().isoformat()}.csv"
    if generated:
        source_name += " (generated on load)"
    return df, source_name, source_path


def filter_campaign_data(
    df: pd.DataFrame,
    start_date: pd.Timestamp,
    end_date: pd.Timestamp,
    sources: list[str],
    campaigns: list[str],
    source_media: list[str],
    countries: list[str],
    industries: list[str],
) -> pd.DataFrame:
    filtered = df[
        (df["date"] >= start_date)
        & (df["date"] <= end_date)
        & (df["source"].isin(sources))
        & (df["campaign_name"].isin(campaigns))
        & (df["source_medium"].isin(source_media))
        & (df["country"].isin(countries))
        & (df["industry"].isin(industries))
    ]
    return filtered.copy()


def summarize_performance(df: pd.DataFrame) -> dict[str, float]:
    spend = float(df["spend"].sum())
    impressions = float(df["impressions"].sum())
    clicks = float(df["clicks"].sum())
    conversions = float(df["conversions"].sum())
    revenue = float(df["revenue"].sum()) if "revenue" in df.columns else 0.0
    return {
        "spend": spend,
        "impressions": impressions,
        "clicks": clicks,
        "conversions": conversions,
        "revenue": revenue,
        "ctr": safe_divide(clicks, impressions),
        "cpc": safe_divide(spend, clicks),
        "cpa": safe_divide(spend, conversions),
        "roas": safe_divide(revenue, spend),
    }


def metric_delta(df: pd.DataFrame, metric: str) -> float:
    dates = sorted(df["date"].dropna().unique())
    if len(dates) < 4:
        return 0.0

    midpoint = len(dates) // 2
    early = summarize_performance(df[df["date"].isin(dates[:midpoint])])
    late = summarize_performance(df[df["date"].isin(dates[midpoint:])])
    early_value = early.get(metric, 0.0)
    late_value = late.get(metric, 0.0)
    return safe_divide(late_value - early_value, abs(early_value))


def format_delta(value: float, lower_is_better: bool = False) -> str:
    if value == 0:
        return "0.0%"
    marker = "▼" if value < 0 else "▲"
    return f"{marker} {abs(value) * 100:.1f}%"


def delta_color(value: float, lower_is_better: bool = False) -> str:
    good = value < 0 if lower_is_better else value > 0
    return "#16a34a" if good else "#dc2626"


def platform_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary = (
        df.groupby("source_label", as_index=False)[METRIC_COLUMNS]
        .sum()
        .sort_values("spend", ascending=False)
    )
    summary["ctr"] = summary.apply(lambda row: safe_divide(row["clicks"], row["impressions"]), axis=1)
    summary["cpc"] = summary.apply(lambda row: safe_divide(row["spend"], row["clicks"]), axis=1)
    summary["cpa"] = summary.apply(lambda row: safe_divide(row["spend"], row["conversions"]), axis=1)
    summary["roas"] = summary.apply(lambda row: safe_divide(row["revenue"], row["spend"]), axis=1)
    return summary


def campaign_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary = (
        df.groupby(["campaign_name", "source_label"], as_index=False)[METRIC_COLUMNS]
        .sum()
        .sort_values(["conversions", "spend"], ascending=[False, False])
    )
    summary["ctr"] = summary.apply(lambda row: safe_divide(row["clicks"], row["impressions"]), axis=1)
    summary["cpc"] = summary.apply(lambda row: safe_divide(row["spend"], row["clicks"]), axis=1)
    summary["cpa"] = summary.apply(lambda row: safe_divide(row["spend"], row["conversions"]), axis=1)
    summary["roas"] = summary.apply(lambda row: safe_divide(row["revenue"], row["spend"]), axis=1)
    return summary


def time_series(df: pd.DataFrame, grain: str) -> pd.DataFrame:
    daily = df.copy()
    if grain == "Week":
        daily["period"] = daily["date"].dt.to_period("W").dt.start_time
        label_format = "%b %d"
    elif grain == "Month":
        daily["period"] = daily["date"].dt.to_period("M").dt.start_time
        label_format = "%b %Y"
    else:
        daily["period"] = daily["date"]
        label_format = "%b %d"

    trend = (
        daily.groupby("period", as_index=False)[METRIC_COLUMNS]
        .sum()
        .sort_values("period")
    )
    trend["ctr"] = trend.apply(lambda row: safe_divide(row["clicks"], row["impressions"]), axis=1)
    trend["cpc"] = trend.apply(lambda row: safe_divide(row["spend"], row["clicks"]), axis=1)
    trend["cpa"] = trend.apply(lambda row: safe_divide(row["spend"], row["conversions"]), axis=1)
    trend["roas"] = trend.apply(lambda row: safe_divide(row["revenue"], row["spend"]), axis=1)
    trend["label"] = trend["period"].dt.strftime(label_format)
    return trend


def available_trend_grains(df: pd.DataFrame) -> list[str]:
    options = ["Day"]
    for grain in ["Week", "Month"]:
        if len(time_series(df, grain)) > 1:
            options.append(grain)
    return options


def reset_invalid_widget_value(key: str, allowed_values: list[str], default_value: str) -> None:
    if st.session_state.get(key) not in allowed_values:
        st.session_state[key] = default_value


def reset_invalid_date_range(key: str, min_date: object, max_date: object) -> None:
    value = st.session_state.get(key)
    if not isinstance(value, tuple) or len(value) != 2:
        st.session_state[key] = (min_date, max_date)
        return

    start, end = value
    if start < min_date or end > max_date or start > end:
        st.session_state[key] = (min_date, max_date)


def money(value: float) -> str:
    return f"${value:,.0f}" if abs(value) >= 100 else f"${value:,.2f}"


def number(value: float) -> str:
    return f"{value:,.0f}"


def percent(value: float) -> str:
    return f"{value * 100:.2f}%"


def inject_css() -> None:
    st.markdown(
        """
        <style>
        :root {
            --page-bg: #eef3f8;
            --ink: #0f172a;
            --muted: #475569;
            --line: #d8e1ec;
            --panel: #ffffff;
            --navy: #071623;
        }
        [data-testid="stAppViewContainer"] {
            background: var(--page-bg);
        }
        [data-testid="stHeader"] {
            background: transparent;
        }
        [data-testid="stToolbar"] {
            display: none;
        }
        [data-testid="stSidebar"] {
            background: #ffffff;
            border-right: 1px solid var(--line);
        }
        [data-testid="stSidebar"] hr {
            border: 0;
            border-top: 1px solid #e2e8f0;
            margin: 1.2rem 0;
        }
        [data-testid="stSidebar"] label,
        [data-testid="stSidebar"] .stMarkdown p {
            color: #334155;
            font-size: 0.88rem;
            font-weight: 650;
        }
        [data-testid="stSidebar"] h1 {
            color: var(--ink);
            font-size: 1.2rem;
            line-height: 1.15;
            margin-bottom: 0.15rem;
        }
        [data-testid="stSidebar"] h3 {
            color: #0f172a;
            font-size: 0.78rem;
            font-weight: 800;
            margin: 0.8rem 0 0.25rem;
            text-transform: uppercase;
        }
        [data-testid="stSidebar"] [data-testid="stCaptionContainer"] {
            color: #64748b;
            font-size: 0.82rem;
            line-height: 1.4;
        }
        [data-testid="stFileUploaderDropzone"] {
            background: #f8fafc;
            border: 1px dashed #94a3b8;
            border-radius: 8px;
        }
        [data-testid="stFileUploaderDropzone"] small,
        [data-testid="stFileUploaderDropzone"] span {
            color: #334155;
        }
        .stDownloadButton button {
            background: #0f766e;
            border: 1px solid #0f766e;
            border-radius: 8px;
            color: #ffffff;
            font-weight: 700;
        }
        .stDownloadButton button:hover {
            background: #115e59;
            border-color: #115e59;
            color: #ffffff;
        }
        [data-baseweb="tag"] {
            background: #2563eb !important;
            border-radius: 6px !important;
            color: #ffffff !important;
        }
        [data-baseweb="tag"] span {
            color: #ffffff !important;
        }
        .main .block-container {
            max-width: 1360px;
            padding-top: 0.75rem;
            padding-bottom: 2.5rem;
        }
        h1, h2, h3, p, div, span {
            letter-spacing: 0;
        }
        .topbar {
            align-items: center;
            background: linear-gradient(135deg, #061526 0%, #09233f 100%);
            border-radius: 0 0 8px 8px;
            box-shadow: 0 12px 30px rgba(7, 22, 35, 0.13);
            color: #ffffff;
            display: flex;
            justify-content: space-between;
            margin: -0.75rem -0.25rem 1rem;
            min-height: 64px;
            padding: 13px 22px;
        }
        .brand-lockup {
            align-items: center;
            display: flex;
            gap: 10px;
        }
        .brand-mark {
            align-items: center;
            border: 1px solid rgba(255,255,255,0.36);
            border-radius: 999px;
            display: flex;
            font-size: 1.15rem;
            font-weight: 850;
            height: 38px;
            justify-content: center;
            width: 38px;
        }
        .brand-title {
            color: #ffffff;
            font-size: 1.02rem;
            font-weight: 800;
            line-height: 1.1;
        }
        .brand-subtitle {
            color: #cbd5e1;
            font-size: 0.78rem;
            margin-top: 3px;
        }
        .topbar-meta {
            align-items: center;
            color: #e2e8f0;
            display: flex;
            flex-wrap: wrap;
            font-size: 0.78rem;
            gap: 10px;
            justify-content: flex-end;
        }
        .topbar-pill {
            background: rgba(255, 255, 255, 0.08);
            border: 1px solid rgba(226, 232, 240, 0.18);
            border-radius: 8px;
            padding: 8px 10px;
        }
        .masthead {
            background: linear-gradient(135deg, #071623 0%, #0b2440 58%, #12325a 100%);
            border: 1px solid #17345a;
            border-radius: 8px;
            box-shadow: 0 18px 42px rgba(7, 22, 35, 0.18);
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 28px;
            margin-bottom: 20px;
            min-height: 148px;
            padding: 22px 24px;
            position: relative;
            overflow: hidden;
        }
        .masthead:after {
            background: #22d3ee;
            bottom: 0;
            content: "";
            height: 4px;
            left: 0;
            position: absolute;
            width: 35%;
        }
        .masthead-title {
            color: #ffffff !important;
            font-size: 2rem;
            font-weight: 760;
            line-height: 1.12;
            margin: 0;
        }
        .masthead-copy {
            color: #cbd5e1 !important;
            font-size: 0.98rem;
            line-height: 1.55;
            margin: 10px 0 0;
            max-width: 760px;
        }
        .lineage-chip {
            background: rgba(255, 255, 255, 0.09);
            border: 1px solid rgba(226, 232, 240, 0.22);
            border-radius: 8px;
            color: #e2e8f0;
            font-size: 0.78rem;
            line-height: 1.45;
            max-width: 360px;
            padding: 12px 14px;
        }
        .status-card {
            background: #f8fafc;
            border: 1px solid #d8e1ec;
            border-radius: 8px;
            color: #334155;
            font-size: 0.8rem;
            line-height: 1.35;
            padding: 10px 11px;
        }
        .status-ok {
            color: #0f766e;
            font-weight: 850;
        }
        .metric-card {
            background: #ffffff;
            border: 1px solid var(--line);
            border-left: 4px solid var(--accent);
            border-radius: 8px;
            box-shadow: 0 10px 22px rgba(15, 23, 42, 0.06);
            display: grid;
            gap: 2px 10px;
            grid-template-columns: 42px minmax(0, 1fr);
            min-height: 92px;
            padding: 10px 11px;
        }
        .metric-head {
            align-items: center;
            display: flex;
            gap: 8px;
            grid-column: 2;
            margin-bottom: 0;
        }
        .metric-swatch {
            background: var(--accent);
            border-radius: 999px;
            display: inline-block;
            height: 7px;
            width: 7px;
        }
        .metric-icon {
            align-items: center;
            background: color-mix(in srgb, var(--accent), white 84%);
            border-radius: 7px;
            color: var(--accent);
            display: flex;
            font-size: 1.25rem;
            font-weight: 850;
            grid-column: 1;
            grid-row: 1 / 4;
            height: 36px;
            justify-content: center;
            margin-top: 5px;
            width: 36px;
        }
        .metric-label {
            color: #0f172a;
            font-size: 0.68rem;
            font-weight: 720;
            overflow-wrap: anywhere;
        }
        .metric-value {
            color: var(--ink);
            font-size: 1.2rem;
            font-weight: 780;
            grid-column: 2;
            line-height: 1.1;
            margin-bottom: 1px;
            overflow-wrap: anywhere;
        }
        .metric-note {
            color: #64748b;
            font-size: 0.66rem;
            grid-column: 2;
            line-height: 1.25;
            overflow-wrap: anywhere;
        }
        .section-title {
            color: var(--ink);
            font-size: 1.02rem;
            font-weight: 760;
            margin: 16px 0 10px;
        }
        .section-row {
            align-items: center;
            display: flex;
            justify-content: space-between;
            gap: 12px;
            margin: 16px 0 10px;
        }
        .section-row .section-title {
            margin: 0;
        }
        .mode-tabs {
            align-items: center;
            background: #ffffff;
            border: 1px solid #d8e1ec;
            border-radius: 8px;
            display: flex;
            gap: 4px;
            padding: 4px;
        }
        .mode-tab {
            border-radius: 6px;
            color: #475569;
            font-size: 0.78rem;
            font-weight: 750;
            padding: 6px 10px;
        }
        .mode-tab-active {
            background: #2563eb;
            color: #ffffff;
        }
        .insight-card {
            background: #ffffff;
            border: 1px solid var(--line);
            border-radius: 8px;
            box-shadow: 0 12px 26px rgba(15, 23, 42, 0.05);
            min-height: 132px;
            padding: 15px 16px;
        }
        .insight-kicker {
            color: #0f766e;
            font-size: 0.75rem;
            font-weight: 720;
            margin-bottom: 8px;
            text-transform: uppercase;
        }
        .insight-main {
            color: var(--ink);
            font-size: 1.05rem;
            font-weight: 740;
            line-height: 1.3;
            margin-bottom: 8px;
        }
        .insight-detail {
            color: var(--muted);
            font-size: 0.86rem;
            line-height: 1.45;
        }
        .stPlotlyChart {
            background: #ffffff;
            border: 1px solid var(--line);
            border-radius: 8px;
            box-shadow: 0 14px 30px rgba(15, 23, 42, 0.055);
            padding: 8px 8px 4px;
        }
        .legend-row {
            background: #ffffff;
            border: 1px solid var(--line);
            border-radius: 8px;
            box-shadow: 0 14px 30px rgba(15, 23, 42, 0.045);
            font-size: 0.82rem;
            line-height: 1.55;
            margin-top: -0.5rem;
            padding: 12px 14px;
        }
        .legend-item {
            align-items: center;
            display: flex;
            justify-content: space-between;
            gap: 12px;
            padding: 4px 0;
        }
        .legend-name {
            align-items: center;
            color: #334155;
            display: flex;
            gap: 8px;
            min-width: 0;
        }
        .legend-swatch {
            border-radius: 3px;
            display: inline-block;
            height: 10px;
            width: 10px;
        }
        .legend-value {
            color: #0f172a;
            font-weight: 720;
            white-space: nowrap;
        }
        div[data-testid="stDataFrame"] {
            border: 1px solid var(--line);
            border-radius: 8px;
            box-shadow: 0 14px 30px rgba(15, 23, 42, 0.045);
            overflow: hidden;
        }
        .table-footer {
            align-items: center;
            color: #64748b;
            display: flex;
            font-size: 0.78rem;
            justify-content: space-between;
            margin: 8px 2px 0;
        }
        .dictionary {
            background: #f8fafc;
            border: 1px solid #d8e1ec;
            border-radius: 8px;
            color: #334155;
            font-size: 0.78rem;
            line-height: 1.45;
            margin-top: 12px;
            padding: 11px;
        }
        @media (max-width: 900px) {
            .masthead {
                display: block;
                min-height: auto;
            }
            .lineage-chip {
                margin-top: 16px;
                max-width: none;
            }
            .masthead-title {
                font-size: 1.65rem;
            }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def render_topbar(source_note: str, as_of_label: str) -> None:
    st.markdown(
        f"""
        <div class="topbar">
            <div class="brand-lockup">
                <div>
                    <div class="brand-title">Global Ads Performance</div>
                    <div class="brand-subtitle">Media Analytics Dashboard</div>
                </div>
            </div>
            <div class="topbar-meta">
                <div class="topbar-pill"><strong>Source:</strong> {escape(source_note)}</div>
                <div class="topbar-pill"><strong>Data as of:</strong> {escape(as_of_label)}</div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_metric_card(
    label: str,
    value: str,
    note: str,
    accent: str,
    icon: str,
    delta: str,
    delta_tone: str = "#16a34a",
) -> None:
    st.markdown(
        f"""
        <div class="metric-card" style="--accent: {accent};">
            <div class="metric-icon">{escape(icon)}</div>
            <div class="metric-head">
                <span class="metric-swatch"></span>
                <div class="metric-label">{escape(label)}</div>
            </div>
            <div class="metric-value">{escape(value)}</div>
            <div class="metric-note">{escape(note)} <span style="color:{delta_tone};font-weight:800;">{escape(delta)}</span></div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_insight(kicker: str, main: str, detail: str) -> None:
    st.markdown(
        f"""
        <div class="insight-card">
            <div class="insight-kicker">{escape(kicker)}</div>
            <div class="insight-main">{escape(main)}</div>
            <div class="insight-detail">{escape(detail)}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def style_figure(fig: go.Figure, height: int = 360) -> go.Figure:
    fig.update_layout(
        height=height,
        margin=dict(l=24, r=24, t=44, b=24),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="#ffffff",
        font=dict(family="Arial, sans-serif", color="#334155", size=13),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        hovermode="x unified",
        hoverlabel=dict(
            align="left",
            bgcolor="#ffffff",
            bordercolor="#cbd5e1",
            font=dict(color="#0f172a", family="Arial, sans-serif", size=12),
        ),
        title_font=dict(color="#0f172a", size=17),
    )
    fig.update_xaxes(showgrid=False, linecolor="#d8e1ec", tickfont=dict(color="#475569"))
    fig.update_yaxes(gridcolor="#edf2f7", zerolinecolor="#edf2f7", tickfont=dict(color="#475569"))
    return fig


def render_trend_chart(df: pd.DataFrame, grain: str) -> None:
    trend = time_series(df, grain)
    spend_hover = [
        (
            f"<b>{escape(row.label)}</b><br>"
            f"Spend: {money(float(row.spend))}<br>"
            f"Revenue: {money(float(row.revenue))}<br>"
            f"ROAS: {float(row.roas):.2f}x<br>"
            f"CPA: {money(float(row.cpa))}"
        )
        for row in trend.itertuples(index=False)
    ]
    conversion_hover = [
        (
            f"<b>{escape(row.label)}</b><br>"
            f"Conversions: {number(float(row.conversions))}<br>"
            f"Clicks: {number(float(row.clicks))}<br>"
            f"CTR: {percent(float(row.ctr))}<br>"
            f"CPC: {money(float(row.cpc))}"
        )
        for row in trend.itertuples(index=False)
    ]
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(
        go.Scatter(
            x=trend["period"],
            y=trend["spend"],
            name="Spend",
            mode="lines+markers",
            line=dict(color="#2563eb", width=3),
            marker=dict(size=8),
            hovertext=spend_hover,
            hovertemplate="%{hovertext}<extra></extra>",
        ),
        secondary_y=False,
    )
    fig.add_trace(
        go.Bar(
            x=trend["period"],
            y=trend["conversions"],
            name="Conversions",
            marker_color="#0f766e",
            opacity=0.78,
            hovertext=conversion_hover,
            hovertemplate="%{hovertext}<extra></extra>",
        ),
        secondary_y=True,
    )
    fig.update_layout(title="Spend & Conversions Over Time")
    if grain == "Month":
        fig.update_xaxes(tickformat="%b %Y")
    elif grain == "Week":
        fig.update_xaxes(tickformat="%b %d", dtick=7 * 24 * 60 * 60 * 1000)
    else:
        tick_values = trend["period"].iloc[::5].tolist()
        if trend["period"].iloc[-1] not in tick_values:
            tick_values.append(trend["period"].iloc[-1])
        fig.update_xaxes(
            tickmode="array",
            tickvals=tick_values,
            ticktext=[value.strftime("%b %d") for value in tick_values],
        )
    fig.update_yaxes(title_text="Spend", secondary_y=False)
    fig.update_yaxes(title_text="Conversions", secondary_y=True)
    st.plotly_chart(style_figure(fig, 390), width="stretch")


def render_platform_chart(df: pd.DataFrame) -> None:
    summary = platform_summary(df)
    total_spend = float(summary["spend"].sum())
    summary["hover_text"] = summary.apply(
        lambda row: (
            f"<b>{escape(str(row['source_label']))}</b><br>"
            f"Spend: {money(float(row['spend']))}<br>"
            f"Share: {percent(safe_divide(float(row['spend']), total_spend))}<br>"
            f"Conversions: {number(float(row['conversions']))}<br>"
            f"Revenue: {money(float(row['revenue']))}<br>"
            f"ROAS: {float(row['roas']):.2f}x<br>"
            f"CPA: {money(float(row['cpa']))}<br>"
            f"CTR: {percent(float(row['ctr']))}"
        ),
        axis=1,
    )
    fig = px.pie(
        summary,
        names="source_label",
        values="spend",
        color="source_label",
        color_discrete_map=PLATFORM_COLORS,
        hole=0.58,
        title="Spend by Platform",
    )
    fig.update_traces(
        textposition="inside",
        textinfo="percent",
        marker_line=dict(color="#ffffff", width=2),
        hovertext=summary["hover_text"],
        hovertemplate="%{hovertext}<extra></extra>",
    )
    fig.update_layout(showlegend=False)
    st.plotly_chart(style_figure(fig, 300), width="stretch")
    rows = []
    for row in summary.itertuples(index=False):
        color = PLATFORM_COLORS.get(row.source_label, "#64748b")
        share = safe_divide(float(row.spend), float(total_spend))
        rows.append(
            f'<div class="legend-item">'
            f'<div class="legend-name"><span class="legend-swatch" style="background:{color};"></span>{escape(row.source_label)}</div>'
            f'<div class="legend-value">{money(float(row.spend))} ({percent(share)})</div>'
            f'</div>'
        )
    rows.append(
        f'<div class="legend-item" style="border-top:1px solid #e2e8f0;margin-top:6px;padding-top:8px;">'
        f'<div class="legend-name"><strong>Total</strong></div>'
        f'<div class="legend-value">{money(float(total_spend))}</div>'
        f'</div>'
    )
    st.markdown(f'<div class="legend-row">{"".join(rows)}</div>', unsafe_allow_html=True)


def render_efficiency_chart(df: pd.DataFrame) -> None:
    campaigns = campaign_summary(df).query("conversions > 0")
    conversion_threshold = max(1.0, float(campaigns["conversions"].sum()) * 0.0025)
    if len(campaigns) > 20:
        campaigns = campaigns[campaigns["conversions"] >= conversion_threshold]
    summary = campaigns.sort_values("cpa", ascending=True).head(9)
    summary["hover_text"] = summary.apply(
        lambda row: (
            f"<b>{escape(str(row['campaign_name']))}</b><br>"
            f"Platform: {escape(str(row['source_label']))}<br>"
            f"CPA: {money(float(row['cpa']))}<br>"
            f"Spend: {money(float(row['spend']))}<br>"
            f"Conversions: {number(float(row['conversions']))}<br>"
            f"Revenue: {money(float(row['revenue']))}<br>"
            f"CTR: {percent(float(row['ctr']))}<br>"
            f"ROAS: {float(row['roas']):.2f}x"
        ),
        axis=1,
    )
    fig = px.bar(
        summary,
        x="cpa",
        y="campaign_name",
        color="source_label",
        color_discrete_map=PLATFORM_COLORS,
        orientation="h",
        title=f"CPA by Campaign (min. {number(conversion_threshold)} conversions)",
        labels={"campaign_name": "", "cpa": "CPA", "source_label": "Platform"},
    )
    hover_lookup = {
        (str(row.campaign_name), str(row.source_label)): str(row.hover_text)
        for row in summary.itertuples(index=False)
    }
    for trace in fig.data:
        trace.hovertext = [hover_lookup.get((str(campaign), str(trace.name)), "") for campaign in trace.y]
        trace.hovertemplate = "%{hovertext}<extra></extra>"
    fig.update_layout(yaxis=dict(autorange="reversed"))
    st.plotly_chart(style_figure(fig, 390), width="stretch")


def render_takeaways(df: pd.DataFrame) -> None:
    platform = platform_summary(df)
    campaigns = campaign_summary(df)
    top_spend = platform.iloc[0]
    top_conversions = campaigns.sort_values("conversions", ascending=False).iloc[0]
    efficient = campaigns[campaigns["conversions"] > 0].sort_values("cpa", ascending=True).iloc[0]

    col1, col2, col3 = st.columns(3)
    with col1:
        render_insight(
            "Budget concentration",
            f"{top_spend['source_label']} carries {money(top_spend['spend'])} in spend",
            f"{percent(top_spend['spend'] / platform['spend'].sum())} of filtered media spend.",
        )
    with col2:
        render_insight(
            "Conversion leader",
            str(top_conversions["campaign_name"]),
            f"{number(top_conversions['conversions'])} conversions at {money(top_conversions['cpa'])} CPA.",
        )
    with col3:
        render_insight(
            "Efficiency watch",
            str(efficient["campaign_name"]),
            f"Lowest CPA in the filtered view: {money(efficient['cpa'])}.",
        )


def render_campaign_table(df: pd.DataFrame) -> None:
    leaderboard = campaign_summary(df).copy()
    leaderboard.insert(0, "rank", range(1, len(leaderboard) + 1))
    total_campaigns = len(leaderboard)
    leaderboard = leaderboard.head(10)
    leaderboard["ctr"] = leaderboard["ctr"].map(percent)
    leaderboard["spend"] = leaderboard["spend"].map(money)
    leaderboard["cpc"] = leaderboard["cpc"].map(money)
    leaderboard["cpa"] = leaderboard["cpa"].map(money)
    leaderboard["revenue"] = leaderboard["revenue"].map(money)
    leaderboard["roas"] = leaderboard["roas"].map(lambda value: f"{value:.2f}x")
    leaderboard["impressions"] = leaderboard["impressions"].map(number)
    leaderboard["clicks"] = leaderboard["clicks"].map(number)
    leaderboard["conversions"] = leaderboard["conversions"].map(number)
    leaderboard = leaderboard[
        [
            "rank",
            "campaign_name",
            "source_label",
            "spend",
            "impressions",
            "clicks",
            "conversions",
            "revenue",
            "ctr",
            "cpc",
            "cpa",
            "roas",
        ]
    ]
    leaderboard.columns = [
        "Rank",
        "Campaign",
        "Platform",
        "Spend",
        "Impressions",
        "Clicks",
        "Conversions",
        "Revenue",
        "CTR",
        "CPC",
        "CPA",
        "ROAS",
    ]
    st.dataframe(leaderboard, width="stretch", hide_index=True, height=260)
    st.markdown(
        f"""
        <div class="table-footer">
            <span>Showing 1 to {len(leaderboard)} of {total_campaigns} campaigns</span>
            <span>Rows per page: {len(leaderboard)}</span>
        </div>
        """,
        unsafe_allow_html=True,
    )


def main() -> None:
    st.set_page_config(
        page_title="Global Ads Performance",
        page_icon="",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    inject_css()

    with st.sidebar:
        st.title("Media Analytics Dashboard")
        st.markdown("### Data")
        selected_dataset = st.selectbox(
            "Dataset",
            options=list(DATASETS),
            format_func=lambda dataset_id: DATASETS[dataset_id]["label"],
            index=list(DATASETS).index(DEFAULT_DATASET_ID),
            key="dataset_filter",
        )
        st.caption(DATASETS[selected_dataset]["source_detail"])
        uploaded = st.file_uploader("Upload unified campaign CSV", type=["csv"])

    if uploaded is not None:
        try:
            df = prepare_campaign_data(pd.read_csv(uploaded))
        except ValueError as exc:
            st.error(str(exc))
            st.stop()
        source_note = f"Uploaded file: {uploaded.name}"
        source_path = uploaded.name
        dataset_label = "Uploaded CSV"
        as_of_label = pd.Timestamp(df["date"].max()).strftime("%b %d, %Y")
    else:
        df, source_note, source_path = load_dashboard_dataset(str(selected_dataset))
        dataset_label = DATASETS[str(selected_dataset)]["label"]
        as_of_label = DATASETS[str(selected_dataset)]["as_of"]
    df = ensure_dashboard_columns(df)

    min_date = df["date"].min().date()
    max_date = df["date"].max().date()
    if not as_of_label:
        as_of_label = pd.Timestamp(max_date).strftime("%b %d, %Y")
    label_to_source = dict(zip(df["source_label"], df["source"]))
    platform_labels = sorted(label_to_source)
    source_media = sorted(df["source_medium"].unique())
    campaign_names = sorted(df["campaign_name"].unique())
    country_names = sorted(df["country"].unique())
    industry_names = sorted(df["industry"].unique())
    test_campaign_count = int(df["campaign_name"].str.contains("test", case=False, na=False).sum())

    reset_invalid_date_range("date_filter", min_date, max_date)
    reset_invalid_widget_value("platform_filter", ["All Platforms"] + platform_labels, "All Platforms")
    reset_invalid_widget_value("campaign_filter", ["All Campaigns"] + campaign_names, "All Campaigns")
    reset_invalid_widget_value("medium_filter", ["All Types"] + source_media, "All Types")
    reset_invalid_widget_value("country_filter", ["All Countries"] + country_names, "All Countries")
    reset_invalid_widget_value("industry_filter", ["All Industries"] + industry_names, "All Industries")
    with st.sidebar:
        st.markdown(
            f"""
            <div class="status-card">
                <span class="status-ok">Validated</span><br>
                {len(df):,} rows loaded from {escape(dataset_label)}.<br>
                <span style="color:#64748b;">{escape(str(source_path))}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.markdown("---")
        st.markdown("### Filters")
        if st.button("Reset filters", use_container_width=True):
            for key in [
                "date_filter",
                "platform_filter",
                "campaign_filter",
                "medium_filter",
                "country_filter",
                "industry_filter",
                "include_test_campaigns",
                "trend_mode",
            ]:
                st.session_state.pop(key, None)
        selected_dates = st.date_input(
            "Date range",
            value=(min_date, max_date),
            min_value=min_date,
            max_value=max_date,
            key="date_filter",
        )
        selected_platform = st.selectbox(
            "Platform",
            options=["All Platforms"] + platform_labels,
            index=0,
            key="platform_filter",
        )
        selected_campaign = st.selectbox(
            "Campaign",
            options=["All Campaigns"] + campaign_names,
            index=0,
            key="campaign_filter",
        )
        selected_source_media = st.selectbox(
            "Source / Medium",
            options=["All Types"] + source_media,
            index=0,
            key="medium_filter",
        )
        selected_country = st.selectbox(
            "Country",
            options=["All Countries"] + country_names,
            index=0,
            key="country_filter",
        )
        selected_industry = st.selectbox(
            "Industry",
            options=["All Industries"] + industry_names,
            index=0,
            key="industry_filter",
        )
        include_test_campaigns = False
        if test_campaign_count:
            include_test_campaigns = st.checkbox(
                f"Include test campaigns ({test_campaign_count:,})",
                value=False,
                key="include_test_campaigns",
            )

    if isinstance(selected_dates, tuple) and len(selected_dates) == 2:
        start_date, end_date = selected_dates
    else:
        start_date = end_date = selected_dates

    selected_platforms = platform_labels if selected_platform == "All Platforms" else [selected_platform]
    selected_campaigns = campaign_names if selected_campaign == "All Campaigns" else [selected_campaign]
    selected_sources = [label_to_source[label] for label in selected_platforms]
    selected_media = source_media if selected_source_media == "All Types" else [selected_source_media]
    selected_countries = country_names if selected_country == "All Countries" else [selected_country]
    selected_industries = industry_names if selected_industry == "All Industries" else [selected_industry]
    filtered = filter_campaign_data(
        df=df,
        start_date=pd.Timestamp(start_date),
        end_date=pd.Timestamp(end_date),
        sources=selected_sources,
        campaigns=selected_campaigns,
        source_media=selected_media,
        countries=selected_countries,
        industries=selected_industries,
    )
    if not include_test_campaigns:
        filtered = filtered[~filtered["campaign_name"].str.contains("test", case=False, na=False)].copy()

    with st.sidebar:
        st.markdown("---")
        st.download_button(
            "Download filtered CSV",
            data=filtered.drop(columns=["source_label", "source_medium"]).to_csv(index=False),
            file_name="filtered_campaign_daily.csv",
            mime="text/csv",
            disabled=filtered.empty,
        )
        st.markdown(
            """
            <div class="dictionary">
                <strong>Data dictionary</strong><br>
                Spend, revenue, impressions, clicks, conversions, CTR, CPC, CPA, and ROAS are normalized at the
                daily campaign grain.
            </div>
            """,
            unsafe_allow_html=True,
        )

    render_topbar(source_note, as_of_label)

    if filtered.empty:
        st.warning("No rows match the selected filters.")
        st.stop()

    totals = summarize_performance(filtered)
    deltas = {
        "spend": metric_delta(filtered, "spend"),
        "conversions": metric_delta(filtered, "conversions"),
        "cpa": metric_delta(filtered, "cpa"),
        "ctr": metric_delta(filtered, "ctr"),
        "cpc": metric_delta(filtered, "cpc"),
        "revenue": metric_delta(filtered, "revenue"),
        "roas": metric_delta(filtered, "roas"),
    }

    metric_cards = [
        (
            "Total Spend",
            money(totals["spend"]),
            "#2563eb",
            "$",
            format_delta(deltas["spend"]),
            delta_color(deltas["spend"]),
        ),
        (
            "Conversions",
            number(totals["conversions"]),
            "#0f766e",
            "+",
            format_delta(deltas["conversions"]),
            delta_color(deltas["conversions"]),
        ),
        (
            "CPA",
            money(totals["cpa"]),
            "#db2777",
            "@",
            format_delta(deltas["cpa"], lower_is_better=True),
            delta_color(deltas["cpa"], lower_is_better=True),
        ),
        (
            "CTR",
            percent(totals["ctr"]),
            "#f59e0b",
            "%",
            format_delta(deltas["ctr"]),
            delta_color(deltas["ctr"]),
        ),
        (
            "CPC",
            money(totals["cpc"]),
            "#7c3aed",
            ">",
            format_delta(deltas["cpc"], lower_is_better=True),
            delta_color(deltas["cpc"], lower_is_better=True),
        ),
        (
            "Revenue",
            money(totals["revenue"]),
            "#14b8a6",
            "R",
            format_delta(deltas["revenue"]),
            delta_color(deltas["revenue"]),
        ),
        (
            "ROAS",
            f"{totals['roas']:.2f}x",
            "#ef4444",
            "x",
            format_delta(deltas["roas"]),
            delta_color(deltas["roas"]),
        ),
    ]
    metric_cols = st.columns(7, gap="small")
    for metric_col, (label, value, accent, icon, delta, tone) in zip(metric_cols, metric_cards):
        with metric_col:
            render_metric_card(
                label,
                value,
                "vs first half of range",
                accent,
                icon,
                delta,
                tone,
            )

    trend_options = available_trend_grains(filtered)
    reset_invalid_widget_value("trend_mode", trend_options, trend_options[0])
    trend_title_col, trend_control_col = st.columns([3, 1])
    with trend_title_col:
        st.markdown('<div class="section-title">Performance Trend</div>', unsafe_allow_html=True)
    with trend_control_col:
        trend_mode = st.radio(
            "Trend grain",
            options=trend_options,
            key="trend_mode",
            horizontal=True,
            label_visibility="collapsed",
        )
    trend_mode = trend_mode or trend_options[0]
    render_trend_chart(filtered, str(trend_mode))

    chart_cols = st.columns(2)
    with chart_cols[0]:
        render_platform_chart(filtered)
    with chart_cols[1]:
        render_efficiency_chart(filtered)

    st.markdown('<div class="section-title">Analyst Takeaways</div>', unsafe_allow_html=True)
    render_takeaways(filtered)

    st.markdown('<div class="section-title">Campaign Leaderboard</div>', unsafe_allow_html=True)
    render_campaign_table(filtered)

    st.caption(
        "Lineage: data/raw platform extracts -> pipeline validation and normalization -> "
        "output/unified_campaign_daily.csv -> Streamlit dashboard."
    )


if __name__ == "__main__":
    main()
